[project]
name = "pySigma-validators-sigmahq"
version = "0.20.3"
description = "pySigma SigmaHQ validators"
license = "LGPL-2.1-only"
readme = "README.md"
requires-python = ">=3.10,<4.0"

authors = [
    {name = "François Hubaut", email = "frack113@users.noreply.github.com" }
]

maintainers = [
    {name = "François Hubaut", email = "frack113@users.noreply.github.com" },
    {name = "Christian Burkard", email = "phantinuss@users.noreply.github.com" }
]

keywords = [ "pySigma", "SigmaHQ", "validators"]

dependencies = [
    "pysigma >=1.3",
    "requests >=2.34"
]

[project.urls]
repository = "https://github.com/SigmaHQ/pySigma_validators_sigmaHQ"

[tool.poetry]
packages = [
    { include = "sigma" }
]

[tool.poetry.group.dev.dependencies]
black = "^26.5"
defusedxml = "^0.7"
pytest = "^9.1"
pytest-cov = "^7.1"
mypy = "^2.0"

[dependency-groups]
dev = [
    "black >=26.5,<27",
    "defusedxml >=0.7,<1",
    "pytest >=9.1,<10",
    "pytest-cov >=7.1,<8",
    "mypy >=2.0,<3",
]

[tool.black]
line-length = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
