name: Validate JSON files

on:
    push:
        paths:
            - 'tools/**/*.json'
            - 'json-schema/**/*.json'
    pull_request:
        paths:
            - 'tools/**/*.json'
            - 'json-schema/**/*.json'

jobs:
    validate-json:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v5

          - name: Install Poetry
            run: pipx install poetry

          - name: Set up Python
            uses: actions/setup-python@v6
            with:
              python-version: '3.12'
              cache: poetry

          - name: Install dependencies
            run: poetry install --no-interaction

          - name: Validate JSON files
            run: |
                poetry run check-jsonschema --schemafile ./json-schema/schema_sigmahq_taxonomy.json ./tools/sigmahq_taxonomy.json
                poetry run check-jsonschema --schemafile ./json-schema/schema_sigmahq_filename.json ./tools/sigmahq_filename.json
                poetry run check-jsonschema --schemafile ./json-schema/schema_sigmahq_windows_validator.json ./tools/sigmahq_windows_validator.json
