name: "Update sigmahq_data.py data"

on:
  #push:
  #  branches:
  #      - "*"
  schedule:
    - cron: "0 0 1 * *" # At 00:00 on day-of-month 1.
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pull-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.11
    - name: Execute update_ref.py Script
      run: |
        pip install pySigma~=0.11
        pip install black~=24.4.2
        python tools/update_ref.py https://github.com/SigmaHQ/pySigma-validators-sigmaHQ/raw/refs/heads/main/tools/
        python -m black --line-length 100 sigma/validators/sigmahq/sigmahq_data.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        reviewers: frack113, phantinuss
        delete-branch: true
        commit-message: 'chore: Update sigmahq_data.py from json files'
        branch: 'create-pull-request/update-data'
        title: 'Update sigmahq_data.py from json file'
        body: |
          ### Summary of the Pull Request

          This PR update the validator data from json files

          ### Changelog

          chore: Update sigmahq_data.py from json files
